### ISSUE TITLE
Add more vanilla vehicles to the build menu.

### ISSUE THREAD

**Issue by Sully101x** [phoenixdowngaming/Takistan_Liberation#3]

**Comment by Sully101x** [comment]
The Prowler for sure armed or not but also we don't have access to a regular cargo truck that I can tell in the build menu.

**Comment by stealthypotato** [comment]
Sure, when i get around to it. 

I'm going to leave this issue open and assigned in progress so people can list specific requested vehicles. Not all vehicles requested will necessarily be added, and submitted vehicles should fit the setting and theme of the mission.

**Comment by DanAlbert** [comment]
There was a cargo truck in the build menu at one point. It wasn't the vanilla HEMTT so it had a less recognizable name, but there definitely was one at one point.

**Comment by Sully101x** [comment]
Suggesting the following vehicles after some testing:
*** Adding MH-6 Little Bird to request this afternoon***
1. Merkava MKIV LIC (Vanilla Slammer UP):
Class Name: "B_MBT_01_TUSK_F"
- Reason : RHS Armor is spotty, this will give us a "reliable" MBT for heavy pushes in large battles. This could replace one of the M1 variants in the build menu currently IMO.

2. Badger IFV (Vanilla Marshall): 
Class Name: "B_APC_Wheeled_01_cannon_F"
- Reason: Armored recon. Handles hilly terrain very well. 

3. SOCOM Buggy (MRZR4): 
Class Name: "rhsusf_mrzr4_d"
- Reason: Recon and general utility. Fast in desert terrain.

4. HEMMT Transport Unarmed: 
Class Name: "rhsusf_M977A4_usarmy_d"
- Reason: Transport truck that doesn't require ammo to build (currently only ones avail are M2 variant and require ammo).

Pic of the vehicles in question:
https://steamuserimages-a.akamaihd.net/ugc/919165034658150017/B556813E8CABE88AFFD0F1E21088E777856554BC/

**Comment by DanAlbert** [comment]
I'd opt for the Gorgon over (or in addition to) the Marshall since it gets a TOW.

**Comment by IanZabel** [comment]
I would second the Gorgon request. Its armaments are very similar to the RHS TUSK Bradleys. We consistently encountered problems with the TUSK eating ridiculous amounts of fire from various sources, and I think the wheeled Gorgon compensates for that. The wheels can be destroyed and the turret is not armored. The user will have to use much more caution when driving, something I think helps offset the strong cannon and TOW armament.

I am not sure of a vanilla replacement for the mobile respawn. I think the RHS MRAP we use fits the bill quite well.

I will also second the prowler requests.

**Comment by IanZabel** [comment]
Regarding the Gorgon, If we need to specifically match the NATO tan camo, there are multiple reskins available for all vanilla vehicles.

**Comment by Sully101x** [comment]
Is the Gorgon an OPFOR vehicle? This gives me concern being on a public server (IFF issues). I'll review the customization options for the Gorgon this afternoon. I agree with Ian's synopsis of the capabilities and given the amount of enemy armor and IFVs that show up to fight, I don't think it'll be an unfair advantage. Also if we manage to keep it alive for more than 1 town resupply in the field will become more of a thing. 

There is another IFV type wheeled vehicle (RHS) that has a .50 and an 40mm gun in the turret. I tried it out some last night; it performed marginally on the hills, but I think the Marshall would be better in this slot as it's way faster and would server as a good recon veh.

**Comment by IanZabel** [comment]
The Gorgon is AAF in the base game. It is the Pandur II which is a Portuguese/Czech striker equivalent. I suspect if we make it the same tan as all base game nato vehicles IFF shouldn't be an issue. It's also big enough to fit a bunch'o'dudes and some prisoners. My only issue with the marshall is its limited arsenal and general fatness. The Gorgon seems to drive better / weigh less than the marshall.

**Comment by DanAlbert** [comment]
If we're being pedantic, Portugal and Czechia are part of NATO, so it still counts ;)

**Comment by IanZabel** [comment]
The P in PDG stands for pedantry.

**Comment by Sully101x** [comment]
Suggest moving this to closed as for the time being we aren't adding vanilla vehicles to the mission in keeping with the setting and theme. I will post a new suggestion with a few RHS vehicles that expand capabilities beyond what is already in the build menu.

**Comment by stealthypotato** [comment]
Sully is recompiling a list as issue #11, for clarity and stuff. This list is deprecated, please refer to #11.
