### ISSUE TITLE
Scope doesnt save with loadouts

### ISSUE THREAD

**Issue by ghost** [phoenixdowngaming/Takistan_Liberation#4]
unable to save scope while loading loadouts, just changes to a Yorris J2

**Comment by DanAlbert** [comment]
iirc there's an issue if you also have a scope for your secondary

**Comment by stealthypotato** [comment]
This shouldn't happen with a secondary/sidearm. Steps to reproduce this bug?

There is a known bug if you carry another weapon in your backpack, ie m107 with long range variable zoom scope equipped, and you carry and mp5 or something in your backpack with a scope attached, vanilla ArmA will replace it with the same scope on your m107. This however has nothing to do with your handgun. 

This bug i cannot fix, but if its something different let me know.

**Comment by stealthypotato** [comment]
Tentatively calling this fixed as i cannot reproduce the bug. If it happens again let me know and provide steps on how to cause it, and i'll look into it.
