### ISSUE TITLE
AI shooting Players while unconscious still.

### ISSUE THREAD

**Issue by Sully101x** [phoenixdowngaming/Takistan_Liberation#5]

**Comment by stealthypotato** [comment]
The settings on our end are correct, but due to how AI fire their weapons and how ACE now handles uncon, this is unfortunately unfixable on our end without modifying ACE.

**Comment by stealthypotato** [comment]
Have an idea which will require testing. Assume the above applies, but i'll see what i can do.

**Comment by stealthypotato** [comment]
Unfortunately AI will finish their current "burst" even if the target is recognized as down, and they don't select a new target until a ceased firing eventhandler goes off. Unfortunately this is an ACE change, and until ACE does something about it we're SoL. I'll keep looking into trying to fix it on our end, or at least replace certain vehicles that are exacerbating the problem as soon as i find viable replacements.

**Comment by DanAlbert** [comment]
Is this referring to the AI relentlessly shooting unconscious players, or to phantom DShK gunners?

**Comment by Sully101x** [comment]
Confirmed through ACE team this is an ACE medical issue that is fixed on next release.

**Comment by DanAlbert** [comment]
:tada:

Got a link to the upstream bug?

**Comment by Sully101x** [comment]
baermitumlaut [4:53 PM] 
we're aware and have fixed it already


[4:54] 
will be released soon


silentspike [4:54 PM] 
In the announcements channel we have our next release candidate, which includes a fix which makes AI forget about the downed unit

https://github.com/acemod/ACE3/releases/tag/v3.12.1-rc1
