### ISSUE TITLE
Arsenal and blacklist

### ISSUE THREAD

**Issue by Sully101x** [phoenixdowngaming/Takistan_Liberation#6]
There are severe issues with the arsenal at present (SUN 7JAN) and I believe the blacklist is partly the issue. 
1. Severe load times - known issue
2. Randomly removing players whole kit even though player was using the same kit earlier in the same play session (does not contain excluded items)
3. Fill players backpacks with AK mags at times while in the arsenal, and other arsenal general fuckery. 

The second and third issues make the game almost unbearable. Suggest removing until a better solution can be found.

**Comment by DanAlbert** [comment]
Yeah, suggest we revert asap given that pretty much everyone finds this frustrating.
