### ISSUE TITLE
Stepko can't use any of the repair/rearm ace interactions

### ISSUE THREAD

**Issue by Sully101x** [phoenixdowngaming/Takistan_Liberation#7]
Stepko does not get ace repair rearm interactions from the SOV truck.
Tested:
1. Public player with toolkit NOT an engineer - Functions properly
2. PDG Sully and Punk and Irish w/toolkit and NOT engineer - Functions properly.
3. Stepko in an engineer slot and with a toolkit - does not give repair options, rearm options, nor configure pylons on aircraft when it works for others. 

Recommended COA:
1. Player reinstalls windows.
2. Unknown

**Comment by DanAlbert** [comment]
Both cases 1 and 2 were not engineers. Any chance Stepko can do it if he's NOT an engineer?

**Comment by Sully101x** [comment]
Error on my part. He tried both in engineer slot and in a different slot.

**Comment by Sully101x** [comment]
Error fixed. Stepko was using an outdated mod. Will update with details when I get them from him.

**Comment by Sully101x** [comment]
Stepko was connecting using the Vanilla launcher. His workshop version of ACE was somehow outdated or corrupted. Fixed by using Arma3Sync

**Comment by DanAlbert** [comment]
Probably worth someone else checking that they can do these things with the vanilla launcher.
