### ISSUE TITLE
Suggestion: Remove NV Scope Blur

### ISSUE THREAD

**Issue by Sully101x** [phoenixdowngaming/Takistan_Liberation#9]
I feel the scope blur effect while in night vision does not add to the experience but detracts. Also physically pains me when looking through it long enough. NV is already completely disabled for use in long range scopes (need to test and confirm today but I think that this is the default either through ACE or vanilla). @stealthypotato let me know if you want me to post a poll on the forums regarding this setting.

**Comment by stealthypotato** [comment]
No poll needed, easily tweaked setting. We'll do this and your vehicle list as a sort of impromptu training for server edits and github.
